name: 15 - Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.x, 22.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 18.x
          - os: ubuntu-latest
            node-version: 22.x
            tag: experimental
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: |
          echo "Running tests on ${{ matrix.os }} using Node version ${{ matrix.node-version }}"
      - name: Upload test results
        run: echo "Uploading test results"
  include-examples:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        exclude:
          - color: green
            shape: circle
        include:
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100
          # A new job for red-triangle-- but the size and opacity facets are *not* added automatically
          - color: red
            shape: triangle
          # Opacity will be added to all jobs as it's not an override
          - opacity: 50
          - color: green
            shape: circle
            size: medium
    steps:
      - name: Dummy
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}"-${{ matrix.opacity }}
