name: 15 - Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.x, 22.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 18.x
          - os: ubuntu-latest
            node-version: 22.x
            tag: experimental
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail is experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Run tests
        run: |
          echo "Running tests on ${{ matrix.os }} using Node version ${{ matrix.node-version }}"
          sleep 10
      - name: Upload test results
        run: echo "Uploading test results"
  include-examples:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include:
          - colors: red
            shape: triangle
