name: 16 - Environments

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging"
  e2e-test:
    runs-on: ubuntu-latest
    environment: staging
    needs: deploy-staging
    steps:
      - name: End to end test
        run: |
          echo "Running end to end tests in staging"
  deploy-prod-frontend:
    runs-on: ubuntu-latest
    environment: prod
    needs: e2e-test
    steps:
      - name: Deploy to prod
        run: |
          echo "Deploying prod frontend"
  deploy-prod-backend:
    runs-on: ubuntu-latest
    environment: prod
    needs: e2e-test
    steps:
      - name: Deploy to prod
        run: |
          echo "Deploying prod backend"
