name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite for ${{ inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Which environment to target for dependency installation
        type: choice
        options:
          - dev
          - prod
        default: dev

env:
  working-directory: 17-custom-actions/react-app
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS and NPM Dependencies
        uses: ./.github/actions/composite-cache-dependencies
        with:
          node-version: 22.x
          working-directory: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}
      - name: Tests
        run: npm run test
      - name: Build
        run: npm run build
